config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    resources :rooms, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :rooms  do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings do
    get 'user_bookings', to: 'bookings#index'
  end


  devise_for :users
  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

  before_create :generate_booking_code
  validate :no_overlapping_bookings, :booking_in_present


  def calculate_booking_price
    (booking_end - booking_start).to_i * booking_price
  end

  def booking_period
    (booking_end - booking_start).to_i
  end

  private
  def generate_booking_code
    # Use a combination of attributes or any other logic to generate a unique booking code
    self.booking_code = "#{room.hotel.title[0..2]}#{room.number}-#{SecureRandom.hex(4).upcase}"
  end

  def no_overlapping_bookings
    if overlapping_bookings.any?
      errors.add(:base, "This room is already booked for the selected dates.")
    end
  end

  def overlapping_bookings
    Booking.where(room_id: room_id)
           .where.not(id: id) # Exclude the current booking if it's an update
           .where("(booking_start <= ? AND booking_end >= ?) OR (booking_start <= ? AND booking_end >= ?)",
                  booking_end, booking_end, booking_start, booking_start)
  end

  def booking_in_present
    if booking_start < Date.today || booking_start > booking_end || booking_end < Date.today
      errors.add(:booking, "dates aren't valid")
    elsif booking_start == booking_end
      errors.add( :base,"Please book at least one day")
    end

  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings, dependent: :destroy

  validates :number, presence: true, uniqueness: { scope: :hotel_id, message: "Room with that number already exists" },
            numericality: { only_integer: true, greater_than: 0 }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy

  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
  end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController

  before_action :set_room, only: [:new, :create]

  def index
    if current_user.admin?
      @bookings = Booking.all
    else
      @bookings = current_user.bookings
    end
  end
  def new
    @booking = @room.bookings.new
  end


  def create
    @room = Room.find(params[:room_id])
    @booking = current_user.bookings.build(booking_params)
    @booking.room = @room
    @booking.booking_price = @room.price

    if @booking.save
      redirect_to @room.hotel, notice: 'Booking was successfully created.'
    else
      flash.now[:messages] = @booking.errors.full_messages[0]
      render :new, status: :unprocessable_entity
    end
  end


  private

  def booking_params
    params.require(:booking).permit(:booking_code, :booking_start, :booking_end, :room_id, :booking_price)
  end

  def set_room
    @room = Room.find(params[:room_id])
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]
  before_action :check_admin, except: [:show, :index]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.user_id = current_user.id

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # def create_room
  #
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:title, :address)
    end

  def check_admin
    redirect_to root_path, alert: 'You do not have permission to perform this action.' unless current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :find_hotel, only: [:new, :create, :edit]
  before_action :authorize_admin
  before_action :find_room, only: [:edit, :update, :destroy]
  def new
    @room = @hotel.rooms.build
  end

  def create
    @room = @hotel.rooms.build(room_params)
    if @room.save
      redirect_to @hotel, notice: "Room was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @room = @hotel.rooms.find(params[:id])
  end

  def update
    if @room.update(room_params)
      redirect_to @room.hotel, notice: "Room info updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @room.destroy
    redirect_to @room.hotel, notice: "Room was deleted"
  end

  private
  def find_hotel
    @hotel = Hotel.find(params[:hotel_id])
    unless @hotel
      redirect_to root_path, alert: "Hotel not found"
    end
  end

  def find_room
    @room = Hotel.find(params[:hotel_id]).rooms.find(params[:id])
    redirect_to @hotel, alert: "Room not found" unless @room
  end

  def room_params
    params.require(:room).permit( :price, :description, :number).merge(hotel_id: params[:hotel_id])
  end

  def authorize_admin
    redirect_to root_path, alert: 'You do not have permission to perform this action.' unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/bookings/index.html.erb
<!-- app/views/bookings/index.html.erb -->
<div class="container-extended mt-5">
  <h2>Your Bookings</h2>

  <% if @bookings.any? %>
    <table class="table">
      <thead>
      <tr>
        <th>Booking Code</th>
        <% if current_user.admin? %>
          <th>User</th>
        <% end %>
        <th>Hotel</th>
        <th>Room Number</th>
        <th>Booking Start Date</th>
        <th>Booking End Date</th>
        <% if current_user.admin? %>
          <th>Booking Room Price (per night)</th>
        <% end %>
        <th>Room Price (per night)</th>
        <th>Number of Nights</th>
        <th>Booking Price</th>
      </tr>
      </thead>
      <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.booking_code %></td>

          <% if current_user.admin? %>
            <td><%= booking.user.username %></td>
          <% end %>

          <td><%= booking.room.hotel.title %></td>
          <td><%= booking.room.number %></td>
          <td><%= booking.booking_start.strftime('%B %e, %Y') %></td>
          <td><%= booking.booking_end.strftime('%B %e, %Y') %></td>

          <% if current_user.admin? %>
            <td><%= number_to_currency(booking.booking_price) %></td>
          <% end %>

          <td><%= number_to_currency(booking.room.price) %></td>
          <td><%= booking.booking_period %></td>
          <td><%= number_to_currency(booking.calculate_booking_price) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No bookings available.</p>
  <% end %>
</div>

app/views/bookings/new.html.erb
<!-- app/views/bookings/new.html.erb -->
<div class="container mt-5">
  <h2>New Booking</h2>

  <%= form_with(model: [@room, @booking],class: 'mt-3') do |form| %>


    <div class="mb-3">
      <%= form.label :booking_start, class: 'form-label' %>
      <%= form.date_field :booking_start, class: 'form-control', required: true %>
    </div>

    <div class="mb-3">
      <%= form.label :booking_end, class: 'form-label' %>
      <%= form.date_field :booking_end, class: 'form-control', required: true %>
    </div>


    <%= form.submit 'Create Booking', class: 'btn btn-primary' %>
    <%= link_to "Back to hotel", hotel_path(@room.hotel), class: 'btn btn-secondary' %>

  <% end %>
</div>

app/views/hotels/_form.html.erb
<%#= form_with(model: hotel) do |form| %>
  <%# if hotel.errors.any? %>
<!--    <div style="color: red">-->
<!--      <h2><%#= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>-->

<!--      <ul>-->
        <%# hotel.errors.each do |error| %>
<!--          <li><%#= error.full_message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div>-->
    <%#= form.label :title, style: "display: block" %>
    <%#= form.text_field :title %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.label :address, style: "display: block" %>
    <%#= form.text_field :address %>
<!--  </div>-->
<!--  <br/>-->

<!--  <div>-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>


<%= form_with(model: hotel, class: 'mt-4') do |form| %>
  <% if hotel.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading"> <%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h4>

      <ul>
        <% hotel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Enter hotel title', required: true %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control', placeholder: 'Enter hotel address', required: true %>
  </div>

  <div class="mt-3">
    <%= form.submit 'Save Changes', class: 'btn btn-primary' %>
  </div> <br/>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p>
    <strong>Title:</strong>
    <%= hotel.title %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= hotel.address %>
  </p>

  <p>
    <strong>User:</strong>
    <%= hotel.user_id %>
  </p>

</div>

app/views/hotels/edit.html.erb
<!--<h1>Editing hotel</h1>-->

<%#= render "form", hotel: @hotel %>

<!--<br>-->

<!--<div>-->
<!--  <%#= link_to "Show this hotel", @hotel %> |-->
  <%#= link_to "Back to hotels", hotels_path %>
<!--</div>-->

<div class="container mt-5">
  <h1>Edit <%= @hotel.title %></h1>

  <%= render "form", hotel: @hotel %>

  <div class="mb-4">
    <%= link_to "Show this hotel", @hotel, class: 'btn btn-primary mr-2' %> |
    <%= link_to "Back to hotels", hotels_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/hotels/index.html.erb
<p style="color: green"><%= notice %></p>

<!--<h1>Hotels</h1>-->

<!--<div id="hotels">-->
  <%# @hotels.each do |hotel| %>
    <%#= render hotel %>
<!--    <p>-->
      <%#= link_to "Show this hotel", hotel %>
      <%#= link_to 'Create room' , new_hotel_room_path(hotel) %>

<!--    </p>-->
  <%# end %>
<!--</div>-->

<%#= link_to "New hotel", new_hotel_path %>


<!-- app/views/hotels/index.html.erb -->

<div class="container mt-5">
  <h1 class="mb-4">Hotels
    <% if current_user.admin? %>
      <a href="<%= new_hotel_path %>" class="btn btn-primary">Create new hotel</a>
    <% end %>
  </h1>


  <% @hotels.each do |hotel| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= hotel.title %></h5>
        <p class="card-text"><strong>Address:</strong> <%= hotel.address %></p>
        <a href="<%= hotel_path(hotel) %>" class="btn btn-primary">View Details</a>
        <% if current_user.admin? %>
          <a href="<%= new_hotel_room_path(hotel) %>" class="btn btn-primary">Create new room</a>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
    <%= link_to "Back to hotels", hotels_path, class: 'btn btn-secondary' %>

</div>

app/views/hotels/show.html.erb
<!--<p style="color: green"><%#= notice %></p>-->

<%#= render @hotel %>

<!--<div>-->
<!--  <%#= link_to "Edit this hotel", edit_hotel_path(@hotel) %> |-->
<!--  <%#= link_to "Back to hotels", hotels_path %> |-->


  <%#= button_to "Destroy this hotel", @hotel, method: :delete %>
<!--</div>-->



<div class="container mt-5">
  <h1><%= @hotel.title %></h1>
  <p class="lead"><strong>Address:</strong> <%= @hotel.address %></p>

  <div class="mb-5 d-flex gap-2">
    <% if current_user.admin? %>
      <%= link_to "Edit this hotel", edit_hotel_path(@hotel), class: 'btn btn-primary' %>
      <%= button_to "Destroy this hotel", @hotel, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      <%= link_to "Create new room", new_hotel_room_path(@hotel), class: "btn btn-primary"%>
    <% end %>
    <%= link_to "Back to hotels", hotels_path, class: 'btn btn-secondary' %>

  </div>

  <!-- Rooms List -->
  <h2>Rooms</h2>
  <% if @hotel.rooms.any? %>
    <table class="table">
      <thead>
      <tr>
        <th>Room Number</th>
        <th>Price</th>
        <th>Description</th>
        <th>Actions</th>

      </tr>
      </thead>
      <tbody>
      <% @hotel.rooms.order(:number).each do |room| %>
        <tr>
          <td><%= room.number %></td>
          <td><%= number_to_currency(room.price) %></td>
          <td><%= room.description %></td>
            <td  class="d-flex gap-2">
              <% if current_user.admin? %>

                <%#= link_to 'View Booking', bookings_path, class: 'btn btn-info btn-sm mr-1' %>
                <%= link_to 'Edit', edit_hotel_room_path(@hotel, room), class: 'btn btn-warning btn-sm mr-1' %>
                <%= button_to 'Delete', hotel_room_path(@hotel, room),  method: :delete, data: {turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
              <% else %>
                <%= link_to 'Book room', new_room_booking_path(room), class: 'btn btn-info btn-sm mr-1' %>
              <% end %>
            </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No rooms available for this hotel.</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamHotel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div class="container mt-4">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>" role="alert">
          <%= message %>
        </div>
      <% end %>
    </div>
<!--    <p class="notice"><%#= notice %></p>-->
<!--    <p class="alert"><%#= alert %></p>-->
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="jumbotron">
    <h1 class="display-4">Welcome to Exam Hotel</h1>
    <p class="lead">Your premier destination for booking hotels and rooms.</p>
    <hr class="my-4">
    <p>Explore our selection of hotels and find the perfect room for your stay.</p>
    <% unless user_signed_in? %>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="users/sign_up" role="button">Sign Up</a>
        <a class="btn btn-success btn-lg" href="users/sign_in" role="button">Login</a>
      </p>
      <% else %>
      <%= link_to "Log out", destroy_user_session_path, class: "btn btn-danger btn-lg", data: {turbo_method: :delete}%>
    <% end %>

  </div>
</div>

app/views/rooms/_room.html.erb
<div class="container mt-5">
  <%= form_with(model: [@hotel, @room], class: 'mb-4', local: true) do |form| %>
    <div class="form-group flex-d">
      <%= form.label :number %>
      <%= form.text_field :number, class: 'form-control', placeholder: 'Enter room number', required: true %>

      <% if @room.errors.has_key?(:number) %>
        <small class="text-danger"><%= @room.errors[:number].first %></small>
      <% end %>
    </div>

    <div>
      <%= form.label :price %>
      <%= form.number_field :price, class: 'form-control', placeholder: 'Enter room price', required: true %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control', placeholder: 'Enter room description', rows: 4, required: true %>
    </div>
    <br>



    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to "Back to hotel", hotel_path(@hotel), class: 'btn btn-secondary' %>

  <% end %>
</div>

app/views/rooms/edit.html.erb
<h1 style="margin-left: 310px">Edit Room</h1>

<%= render 'room' %>

app/views/rooms/new.html.erb
<h1 style="margin-left: 310px">New Room</h1>

<%= render 'room' %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href= <%= root_path %> >Exam Hotel</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%= hotels_path %>>Hotels</a>
        </li>

<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Link</a>-->
<!--        </li>-->

        <% if signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              User: <%= current_user.username %>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li><a class="dropdown-item" href=<%= bookings_path %>>Bookings</a></li>

                <% else %>
              <li><a class="dropdown-item" href=<%= bookings_path %>>My bookings</a></li>
              <% end %>
            </ul>
          </li>

          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, class: "nav-link active", data: {turbo_method: :delete}%>
          </li>
        <% end %>

      </ul>


    </div>
  </div>
</nav>